channels:
  - defaults
dependencies:
  - pip
  - ipykernel=5.1.1
  - ipython=7.6.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - jupyter=1.0.0
  - matplotlib=3.1.0
  - notebook=5.7.8
  - numpy=1.16.4
  - pandas=0.24.2
  - patsy=0.5.1
  - python=3.7.3
  - scikit-learn=0.21.2
  - scipy=1.2.1
  - seaborn=0.9.0
  - statsmodels=0.10.0
  - nltk=3.4.3
  - lxml
  - pip:
    - gensim==3.8.0
    - umap-learn==0.3.9
    - pyLDAvis==2.1.2
